# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20180513_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
