# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_warehouse_img_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('location_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_from', to='warehouse.Warehouse')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to', to='warehouse.Warehouse')),
            ],
        ),
    ]
